# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20170716_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='forkstate',
            name='is_currently_forked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='is_up',
            field=models.BooleanField(default=True),
        ),
    ]
