# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20170716_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIP9Fork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('elapsed', models.IntegerField()),
                ('period', models.IntegerField()),
                ('threshold', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='forkstate',
            name='is_currently_forked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='is_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='node',
            name='mtp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='node',
            name='stats_node',
            field=models.BooleanField(default=False),
        ),
    ]
