# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20170718_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIP9Fork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('elapsed', models.IntegerField()),
                ('period', models.IntegerField()),
                ('threshold', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='stats_node',
            field=models.BooleanField(default=False),
        ),
    ]
