# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20170718_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='bip9fork',
            name='since',
            field=models.IntegerField(default=0),
        ),
    ]
