# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_bip9fork_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTFork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('activation_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
