# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_updatelock'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='mtp_fork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.MTFork'),
        ),
        migrations.AddField(
            model_name='node',
            name='sched_forked',
            field=models.BooleanField(default=False),
        ),
    ]
