# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_auto_20170727_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='best_block_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
