# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0018_node_best_block_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='common_ancestor_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='node',
            name='common_ancestor_height',
            field=models.IntegerField(default=0),
        ),
    ]
