# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_auto_20170803_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='last_updated_best',
            field=models.CharField(default='', max_length=64),
        ),
    ]
